[workspace]
resolver = "3"
members = [
  "01-places",
  "02-handles",
  "02-handles/adt_reflect",
  "helpers/macros",
]

[workspace.dependencies]
macros = { path = "helpers/macros" }

proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits", "visit", "visit-mut"] }
