[workspace]
resolver = "3"
members = [
  "design",
  "helpers/adt_reflect",
  "helpers/macros",
  "examples/unnormalized",
]

[workspace.dependencies]
design = { path = "design" }
macros = { path = "helpers/macros" }
adt_reflect = { path = "helpers/adt_reflect" }

proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = [
  "full",
  "extra-traits",
  "visit",
  "visit-mut",
] }
